# Generated by Django 3.0.5 on 2020-05-14 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200424_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TP', 'Track Pants'), ('ET', 'Event T-Shirt'), ('CUT', 'Customized T-Shirt'), ('COT', 'Corporate T-Shirt'), ('GT', 'Graphics T-Shirt'), ('SPT', 'Sports T-Shirt'), ('SUT', 'Sublimation T-Shirt'), ('CT', 'Collar T-Shirt'), ('RNT', 'Round Neck T-Shirt')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
