# Generated by Django 3.0.5 on 2020-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200514_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
