# Generated by Django 3.0.5 on 2020-05-15 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200515_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('TP', 'Track Pants'), ('ET', 'Event T-Shirt'), ('CUT', 'Customized T-Shirt'), ('COT', 'Corporate T-Shirt'), ('GT', 'Graphics T-Shirt'), ('SPT', 'Sports T-Shirt'), ('SUT', 'Sublimation T-Shirt'), ('CT', 'Collar T-Shirt'), ('RNT', 'Round Neck T-Shirt')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
