# Generated by Django 3.0.5 on 2020-05-26 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.CharField(choices=[('B', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
