# Generated by Django 3.0.5 on 2020-05-26 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_item_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sizes',
            new_name='size',
        ),
    ]
