# Generated by Django 3.0.5 on 2020-06-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
