# Generated by Django 3.0.5 on 2020-06-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='core.Variation'),
        ),
    ]
