# Generated by Django 3.0.5 on 2020-07-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_order_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
