# Generated by Django 3.0.5 on 2020-07-23 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_auto_20200723_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllUserProfiles',
            new_name='AllUserProfile',
        ),
    ]
