# Generated by Django 3.0.5 on 2020-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200723_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alluserprofile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='alluserprofile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
